// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/izrada-sajta": {
    params: {};
  };
  "/izrada-sajta-detalji": {
    params: {};
  };
  "/seo-optimizacija-cena": {
    params: {};
  };
  "/seo": {
    params: {};
  };
  "/seo-optimizacija-detalji": {
    params: {};
  };
  "/lokalni-seo-beograd": {
    params: {};
  };
  "/web-dizajn": {
    params: {};
  };
  "/izrada-web-shopa": {
    params: {};
  };
  "/promet-sistem": {
    params: {};
  };
  "/portfolio/:slug": {
    params: {
      "slug": string;
    };
  };
  "/thank-you": {
    params: {};
  };
  "/resources": {
    params: {};
  };
  "/resources/quiz": {
    params: {};
  };
  "/resources/audit": {
    params: {};
  };
  "/resources/guide": {
    params: {};
  };
  "/resources/checklist": {
    params: {};
  };
  "/privacy": {
    params: {};
  };
  "/terms": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/izrada-sajta" | "/izrada-sajta-detalji" | "/seo-optimizacija-cena" | "/seo" | "/seo-optimizacija-detalji" | "/lokalni-seo-beograd" | "/web-dizajn" | "/izrada-web-shopa" | "/promet-sistem" | "/portfolio/:slug" | "/thank-you" | "/resources" | "/resources/quiz" | "/resources/audit" | "/resources/guide" | "/resources/checklist" | "/privacy" | "/terms";
  };
  "home.tsx": {
    id: "home";
    page: "/";
  };
  "izradaSajta.tsx": {
    id: "izradaSajta";
    page: "/izrada-sajta";
  };
  "izradaSajtaDetalji.tsx": {
    id: "izradaSajtaDetalji";
    page: "/izrada-sajta-detalji";
  };
  "seoOptimizacijaCena.tsx": {
    id: "seoOptimizacijaCena";
    page: "/seo-optimizacija-cena";
  } | {
    id: "seoAlias";
    page: "/seo";
  };
  "seoOptimizacijaDetalji.tsx": {
    id: "seoOptimizacijaDetalji";
    page: "/seo-optimizacija-detalji";
  };
  "lokalniSeoBeograd.tsx": {
    id: "lokalniSeoBeograd";
    page: "/lokalni-seo-beograd";
  };
  "webDizajn.tsx": {
    id: "webDizajn";
    page: "/web-dizajn";
  };
  "izradaWebShopa.tsx": {
    id: "izradaWebShopa";
    page: "/izrada-web-shopa";
  };
  "prometSistem.tsx": {
    id: "prometSistem";
    page: "/promet-sistem";
  };
  "portfolioDetail.tsx": {
    id: "portfolioDetail";
    page: "/portfolio/:slug";
  };
  "thankYou.tsx": {
    id: "thankYou";
    page: "/thank-you";
  };
  "resources.tsx": {
    id: "resources";
    page: "/resources";
  };
  "resourcesQuiz.tsx": {
    id: "resourcesQuiz";
    page: "/resources/quiz";
  };
  "resourcesAudit.tsx": {
    id: "resourcesAudit";
    page: "/resources/audit";
  };
  "resourcesGuide.tsx": {
    id: "resourcesGuide";
    page: "/resources/guide";
  };
  "resourcesChecklist.tsx": {
    id: "resourcesChecklist";
    page: "/resources/checklist";
  };
  "privacy.tsx": {
    id: "privacy";
    page: "/privacy";
  };
  "terms.tsx": {
    id: "terms";
    page: "/terms";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "home": typeof import("./src/home.tsx");
  "izradaSajta": typeof import("./src/izradaSajta.tsx");
  "izradaSajtaDetalji": typeof import("./src/izradaSajtaDetalji.tsx");
  "seoOptimizacijaCena": typeof import("./src/seoOptimizacijaCena.tsx");
  "seoAlias": typeof import("./src/seoOptimizacijaCena.tsx");
  "seoOptimizacijaDetalji": typeof import("./src/seoOptimizacijaDetalji.tsx");
  "lokalniSeoBeograd": typeof import("./src/lokalniSeoBeograd.tsx");
  "webDizajn": typeof import("./src/webDizajn.tsx");
  "izradaWebShopa": typeof import("./src/izradaWebShopa.tsx");
  "prometSistem": typeof import("./src/prometSistem.tsx");
  "portfolioDetail": typeof import("./src/portfolioDetail.tsx");
  "thankYou": typeof import("./src/thankYou.tsx");
  "resources": typeof import("./src/resources.tsx");
  "resourcesQuiz": typeof import("./src/resourcesQuiz.tsx");
  "resourcesAudit": typeof import("./src/resourcesAudit.tsx");
  "resourcesGuide": typeof import("./src/resourcesGuide.tsx");
  "resourcesChecklist": typeof import("./src/resourcesChecklist.tsx");
  "privacy": typeof import("./src/privacy.tsx");
  "terms": typeof import("./src/terms.tsx");
};