// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/izrada-sajta-cena": {
    params: {};
  };
  "/izrada-sajta-detalji": {
    params: {};
  };
  "/seo-optimizacija-cena": {
    params: {};
  };
  "/seo": {
    params: {};
  };
  "/seo-optimizacija-detalji": {
    params: {};
  };
  "/web-dizajn": {
    params: {};
  };
  "/izrada-web-shopa": {
    params: {};
  };
  "/funnel": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/promet-sistem": {
    params: {};
  };
  "/portfolio": {
    params: {};
  };
  "/portfolio/:slug": {
    params: {
      "slug": string;
    };
  };
  "/thank-you": {
    params: {};
  };
  "/resources": {
    params: {};
  };
  "/resources/quiz": {
    params: {};
  };
  "/resources/audit": {
    params: {};
  };
  "/resources/guide": {
    params: {};
  };
  "/resources/checklist": {
    params: {};
  };
  "/blog": {
    params: {};
  };
  "/blog/category/:categorySlug": {
    params: {
      "categorySlug": string;
    };
  };
  "/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/privacy": {
    params: {};
  };
  "/terms": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/izrada-sajta-cena" | "/izrada-sajta-detalji" | "/seo-optimizacija-cena" | "/seo" | "/seo-optimizacija-detalji" | "/web-dizajn" | "/izrada-web-shopa" | "/funnel" | "/contact" | "/promet-sistem" | "/portfolio" | "/portfolio/:slug" | "/thank-you" | "/resources" | "/resources/quiz" | "/resources/audit" | "/resources/guide" | "/resources/checklist" | "/blog" | "/blog/category/:categorySlug" | "/blog/:slug" | "/privacy" | "/terms";
  };
  "home.tsx": {
    id: "home";
    page: "/";
  };
  "izradaSajtaCena.tsx": {
    id: "izradaSajtaCena";
    page: "/izrada-sajta-cena";
  };
  "izradaSajtaDetalji.tsx": {
    id: "izradaSajtaDetalji";
    page: "/izrada-sajta-detalji";
  };
  "seoOptimizacijaCena.tsx": {
    id: "seoOptimizacijaCena";
    page: "/seo-optimizacija-cena";
  } | {
    id: "seoAlias";
    page: "/seo";
  };
  "seoOptimizacijaDetalji.tsx": {
    id: "seoOptimizacijaDetalji";
    page: "/seo-optimizacija-detalji";
  };
  "webDizajn.tsx": {
    id: "webDizajn";
    page: "/web-dizajn";
  };
  "izradaWebShopa.tsx": {
    id: "izradaWebShopa";
    page: "/izrada-web-shopa";
  };
  "funnel.tsx": {
    id: "funnel";
    page: "/funnel";
  } | {
    id: "contactAlias";
    page: "/contact";
  };
  "prometSistem.tsx": {
    id: "prometSistem";
    page: "/promet-sistem";
  };
  "portfolio.tsx": {
    id: "portfolio";
    page: "/portfolio";
  };
  "portfolioDetail.tsx": {
    id: "portfolioDetail";
    page: "/portfolio/:slug";
  };
  "thankYou.tsx": {
    id: "thankYou";
    page: "/thank-you";
  };
  "resources.tsx": {
    id: "resources";
    page: "/resources";
  };
  "resourcesQuiz.tsx": {
    id: "resourcesQuiz";
    page: "/resources/quiz";
  };
  "resourcesAudit.tsx": {
    id: "resourcesAudit";
    page: "/resources/audit";
  };
  "resourcesGuide.tsx": {
    id: "resourcesGuide";
    page: "/resources/guide";
  };
  "resourcesChecklist.tsx": {
    id: "resourcesChecklist";
    page: "/resources/checklist";
  };
  "blogHub.tsx": {
    id: "blogHub";
    page: "/blog";
  };
  "blogCategory.tsx": {
    id: "blogCategory";
    page: "/blog/category/:categorySlug";
  };
  "blogPost.tsx": {
    id: "blogPost";
    page: "/blog/:slug";
  };
  "privacy.tsx": {
    id: "privacy";
    page: "/privacy";
  };
  "terms.tsx": {
    id: "terms";
    page: "/terms";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "home": typeof import("./src/home.tsx");
  "izradaSajtaCena": typeof import("./src/izradaSajtaCena.tsx");
  "izradaSajtaDetalji": typeof import("./src/izradaSajtaDetalji.tsx");
  "seoOptimizacijaCena": typeof import("./src/seoOptimizacijaCena.tsx");
  "seoAlias": typeof import("./src/seoOptimizacijaCena.tsx");
  "seoOptimizacijaDetalji": typeof import("./src/seoOptimizacijaDetalji.tsx");
  "webDizajn": typeof import("./src/webDizajn.tsx");
  "izradaWebShopa": typeof import("./src/izradaWebShopa.tsx");
  "funnel": typeof import("./src/funnel.tsx");
  "contactAlias": typeof import("./src/funnel.tsx");
  "prometSistem": typeof import("./src/prometSistem.tsx");
  "portfolio": typeof import("./src/portfolio.tsx");
  "portfolioDetail": typeof import("./src/portfolioDetail.tsx");
  "thankYou": typeof import("./src/thankYou.tsx");
  "resources": typeof import("./src/resources.tsx");
  "resourcesQuiz": typeof import("./src/resourcesQuiz.tsx");
  "resourcesAudit": typeof import("./src/resourcesAudit.tsx");
  "resourcesGuide": typeof import("./src/resourcesGuide.tsx");
  "resourcesChecklist": typeof import("./src/resourcesChecklist.tsx");
  "blogHub": typeof import("./src/blogHub.tsx");
  "blogCategory": typeof import("./src/blogCategory.tsx");
  "blogPost": typeof import("./src/blogPost.tsx");
  "privacy": typeof import("./src/privacy.tsx");
  "terms": typeof import("./src/terms.tsx");
};